### ISSUE TITLE
system.app performance

### ISSUE THREAD

**Issue by NigelGomm** [DougHennig/Ribbon#8]
Doug,

Can i draw your attention to this [https://www.tek-tips.com/viewthread.cfm?qid=1812073](url).

my solution is probably not for everyone.

n

**Comment by DougHennig** [comment]
I've run into performance issues with System.app as well. Not with the Ribbon but with FoxCharts, which is why I ended up creating the Gauge VFPX project. I was never able to figure out what caused the performance issue -- I suspect it was a conflict with different versions of GDIPlus.dll on the user's machine -- but hadn't tried including System.prg in the project.

As this isn't really a Ribbon issue, I'm going to close this issue.
